#!/bin/bash

# since I'm working with coreos vagrant box
# and root path is read-only there I need to specify
# different base path there - empty DOCKER_REMOTE_PATH
# and DOCKER_CLIENT_PATH works fine if you have native docker

APP="${DOCKER_REMOTE_PATH}${PWD#${DOCKER_CLIENT_PATH}}/:/app/src"

docker run -it --rm \
    -w /app \
    -v $APP \
    -v /var/run/docker.sock:/var/run/docker.sock \
    michaloo/node-scheduler
